repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        additional_dependencies: [textual, arrow, types-requests]
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pipenv run pylint
        language: system
        types: [python]
        args: [
            "budgetize",
            "--fail-under=9",
            "--recursive=True",
            "--output-format=colorized"
        ]
